version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-container
    networks:
      webnet:
        ipv4_address: 172.18.0.2
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-container
    networks:
      webnet:
        ipv4_address: 172.18.0.3
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://172.18.0.4:5432/geoip_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: c0lombia
    depends_on:
      - db

  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: postgres-container
    networks:
      webnet:
        ipv4_address: 172.18.0.4
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  webnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

volumes:
  postgres-data:
